# Generated by Django 4.0.2 on 2022-05-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S2200301Client',
            fields=[
                ('clid', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('dob', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(blank=True, max_length=25, null=True)),
                ('contactno', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 's22_003_01_client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S2200301Customer',
            fields=[
                ('cuid2', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('dob', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(blank=True, max_length=25, null=True)),
                ('contactno', models.BigIntegerField(blank=True, null=True)),
                ('customeraddress', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 's22_003_01_customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S2200301Employee',
            fields=[
                ('eid', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('dob', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(blank=True, max_length=25, null=True)),
                ('startdateemployment', models.CharField(blank=True, max_length=25, null=True)),
                ('role', models.CharField(blank=True, max_length=25, null=True)),
                ('contactno', models.BigIntegerField(blank=True, null=True)),
                ('employeeaddress', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 's22_003_01_employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S2200301PropertyDetails',
            fields=[
                ('pid', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('price', models.BigIntegerField()),
                ('builtbycompany', models.CharField(max_length=25)),
                ('parkingspace', models.BigIntegerField()),
                ('garagespace', models.BigIntegerField()),
                ('bedrooms', models.BigIntegerField()),
                ('squarefeet', models.BigIntegerField()),
                ('year', models.BigIntegerField()),
            ],
            options={
                'db_table': 's22_003_01_property_details',
                'managed': False,
            },
        ),
    ]
