# Generated by Django 4.1.3 on 2022-11-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FALL22_S003_14_BOOKINGS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('charges', models.DecimalField(decimal_places=3, max_digits=3)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'FALL22_S003_14_BOOKINGS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FALL22_S003_14_USER_TYPES',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'FALL22_S003_14_USER_TYPES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FALL22_S003_14_USERS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=50)),
                ('is_vaccinated', models.BigIntegerField()),
            ],
            options={
                'db_table': 'FALL22_S003_14_USERS',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='S2200301Client',
        ),
        migrations.DeleteModel(
            name='S2200301Customer',
        ),
        migrations.DeleteModel(
            name='S2200301Employee',
        ),
        migrations.DeleteModel(
            name='S2200301PropertyDetails',
        ),
    ]
