# Generated by Django 4.1.3 on 2022-12-06 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_fall22_s003_14_bookings_fall22_s003_14_user_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FALL22_S003_14_FEEDBACK',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.CharField(max_length=100)),
                ('rating', models.BigIntegerField()),
                ('fk_booking_id', models.ForeignKey(db_column='fk_booking_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='booking_id', to='front.fall22_s003_14_users')),
            ],
        ),
    ]
